# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 13:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.BigIntegerField(verbose_name=9430224)),
                ('flag', models.BooleanField(default=False)),
                ('phone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datas', related_query_name='data', to='Reg.UserData')),
            ],
        ),
    ]
